version: '3.4'

services:
  rivendell:
    image: darrick1/rivendell:latest
    hostname: rivendell
    shm_size: '1gb'
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DB: Rivendell
      RD_MYSQL_USER: rd
      RD_MYSQL_PASS: letmein
      RD_USER: rduser
      RD_USER_PASS: rduser
      RD_GROUP: rivendell
      RD_TIMEZONE: UTC
      RDADMIN_USER: admin
      RDADMIN_PASS: admin
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - rivendell-audio-store-test:/var/snd

    ports:
      - "3389:3389"
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - rivendell-mysql-data-test:/var/lib/mysql
volumes:
  rivendell-mysql-data-test:
  rivendell-audio-store-test:
